### ISSUE TITLE
Improper Token has been passed

### ISSUE THREAD

**Issue by ILUXASAN** [tachycardiazxc/DiscordBot#13]
Привет, увидел твою статью на хабре об этом боте. Попробовал запустить у себя но получил следующую ошибку:
Я однозначно ввел в cfg.py файл актуальный токен, логин в VK проходит нормально. Почитал форумы по поводу данной проблемы, но там были ошибки в коде, тут же я ничего не смог найти в твоём коде, касаемо обработки токена, что могло бы вызвать данную проблему. Токен вставил в кавычки в cfg в виде DISCORD_API_TOKEN="TOKEN_HERE"

D:\VKBOT\DiscordBot-master>D:.\venv\scripts\activate

(venv) D:\VKBOT\DiscordBot-master>python main.py
Media folder checked...
Starting and configuring the bot...
Traceback (most recent call last):
  File "D:\VKBOT\DiscordBot-master\venv\lib\site-packages\discord\http.py", line 300, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "D:\VKBOT\DiscordBot-master\venv\lib\site-packages\discord\http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 36, in <module>
    bot.run(os.getenv("TOKEN"))
  File "D:\VKBOT\DiscordBot-master\venv\lib\site-packages\discord\client.py", line 723, in run
    return future.result()
  File "D:\VKBOT\DiscordBot-master\venv\lib\site-packages\discord\client.py", line 702, in runner
    await self.start(*args, **kwargs)
  File "D:\VKBOT\DiscordBot-master\venv\lib\site-packages\discord\client.py", line 665, in start
    await self.login(*args, bot=bot)
  File "D:\VKBOT\DiscordBot-master\venv\lib\site-packages\discord\client.py", line 511, in login
    await self.http.static_login(token.strip(), bot=bot)
  File "D:\VKBOT\DiscordBot-master\venv\lib\site-packages\discord\http.py", line 304, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000027162321670>
Traceback (most recent call last):
  File "c:\users\ilyar\appdata\local\programs\python\python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "c:\users\ilyar\appdata\local\programs\python\python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "c:\users\ilyar\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "c:\users\ilyar\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by tachycardiazxc** [comment]
хм, сейчас посмотрю

**Comment by tachycardiazxc** [comment]
а откуда ты токен доставал? со вкладки бот?

**Comment by ILUXASAN** [comment]
![image](https://user-images.githubusercontent.com/40594176/185751436-44af64bd-95af-49e0-927c-9988e6c32882.png)
Вот здесь из строки authorization

**Comment by tachycardiazxc** [comment]
что-то явно не оттуда, сейчас я видео запишу, надо будет это в редми потом добавить...

**Comment by tachycardiazxc** [comment]
https://user-images.githubusercontent.com/90278654/185751798-a64ecfbc-04af-4063-acb5-38051651676c.mp4

**Comment by ILUXASAN** [comment]
Огромное спасибо за отклик, теперь все работает. Подскажи, пожалуйста, ещё один момент: в Requirements было указано ffmpeg, папку с ней надо в корень проекта кидать или просто скачать? В проекте ffmpeg также .exe, которые, как я понял через cmd надо запускать

**Comment by tachycardiazxc** [comment]
ffmpeg не надо скидывать в папку проекта и запускать отдельно тоже не надо
все что нужно сделать это распаковать ffmpeg где-то на диске и указать в параметрах среды винды в path путь до bin папки ffmpeg`а
![image](https://user-images.githubusercontent.com/90278654/185752302-9dffd9d3-943d-471a-af98-af1be7cf643f.png)
![image](https://user-images.githubusercontent.com/90278654/185752384-e0a57ef4-e721-4baa-9260-0793c27f07c6.png)

**Comment by ILUXASAN** [comment]
Спасибо за помощь с подробным описанием.

**Comment by tachycardiazxc** [comment]
Рад помочь)
закрываю этот тред, потом добавлю все в редми

**Comment by ILUXASAN** [comment]
Теперь новая проблема, ошибка, связанная с библиотекой Pynacl, я её вручную еще установил, не помогло. Попытался использовать команду ?join, с ?play то же самое.
Ignoring exception in command join:
Traceback (most recent call last):
  File "D:\VKBOT\DiscordBot-master\venv\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\VKBOT\DiscordBot-master\src\discord_bot\client.py", line 211, in connect_
    await channel.connect()
  File "D:\VKBOT\DiscordBot-master\venv\lib\site-packages\discord\abc.py", line 1277, in connect
    voice = cls(client, self)
  File "D:\VKBOT\DiscordBot-master\venv\lib\site-packages\discord\voice_client.py", line 199, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
  File "D:\VKBOT\DiscordBot-master\venv\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "D:\VKBOT\DiscordBot-master\venv\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\VKBOT\DiscordBot-master\venv\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: RuntimeError: PyNaCl library needed in order to use voice

**Comment by tachycardiazxc** [comment]
а ты устанавливал все из requirements.txt файла?
pip install -r requirements.txt
он есть в этом файле
бота запускаешь из под окружения?
.\venv\scripts\activate

**Comment by ILUXASAN** [comment]
Да

**Comment by tachycardiazxc** [comment]
устанавливать requirements.txt файл только после активации окружения, иначе окружение будет пустым

**Comment by ILUXASAN** [comment]
(venv) D:\VKBOT\DiscordBot-master>pip install -r requirements.txt
Requirement already satisfied: m3u8==2.0.0 in d:\vkbot\discordbot-master\venv\lib\site-packages (from -r requirements.txt (line 1)) (2.0.0)
Requirement already satisfied: requests==2.28.1 in d:\vkbot\discordbot-master\venv\lib\site-packages (from -r requirements.txt (line 2)) (2.28.1)
Requirement already satisfied: vk_api==11.9.9 in d:\vkbot\discordbot-master\venv\lib\site-packages (from -r requirements.txt (line 3)) (11.9.9)
Requirement already satisfied: pycryptodome==3.15.0 in d:\vkbot\discordbot-master\venv\lib\site-packages (from -r requirements.txt (line 4)) (3.15.0)
Requirement already satisfied: beautifulsoup4==4.11.1 in d:\vkbot\discordbot-master\venv\lib\site-packages (from -r requirements.txt (line 5)) (4.11.1)
Requirement already satisfied: discord.py==1.7.3 in d:\vkbot\discordbot-master\venv\lib\site-packages (from -r requirements.txt (line 6)) (1.7.3)
Requirement already satisfied: PyNaCl==1.5.0 in d:\vkbot\discordbot-master\venv\lib\site-packages (from -r requirements.txt (line 7)) (1.5.0)
Requirement already satisfied: natsort==8.1.0 in d:\vkbot\discordbot-master\venv\lib\site-packages (from -r requirements.txt (line 8)) (8.1.0)
Requirement already satisfied: iso8601 in d:\vkbot\discordbot-master\venv\lib\site-packages (from m3u8==2.0.0->-r requirements.txt (line 1)) (1.0.2)
Requirement already satisfied: certifi>=2017.4.17 in d:\vkbot\discordbot-master\venv\lib\site-packages (from requests==2.28.1->-r requirements.txt (line 2)) (2022.6.15)
Requirement already satisfied: charset-normalizer<3,>=2 in d:\vkbot\discordbot-master\venv\lib\site-packages (from requests==2.28.1->-r requirements.txt (line 2)) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in d:\vkbot\discordbot-master\venv\lib\site-packages (from requests==2.28.1->-r requirements.txt (line 2)) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\vkbot\discordbot-master\venv\lib\site-packages (from requests==2.28.1->-r requirements.txt (line 2)) (1.26.11)
Requirement already satisfied: soupsieve>1.2 in d:\vkbot\discordbot-master\venv\lib\site-packages (from beautifulsoup4==4.11.1->-r requirements.txt (line 5)) (2.3.2.post1)
Requirement already satisfied: aiohttp<3.8.0,>=3.6.0 in d:\vkbot\discordbot-master\venv\lib\site-packages (from discord.py==1.7.3->-r requirements.txt (line 6)) (3.7.4.post0)
Requirement already satisfied: cffi>=1.4.1 in d:\vkbot\discordbot-master\venv\lib\site-packages (from PyNaCl==1.5.0->-r requirements.txt (line 7)) (1.15.1)
Requirement already satisfied: multidict<7.0,>=4.5 in d:\vkbot\discordbot-master\venv\lib\site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py==1.7.3->-r requirements.txt (line 6)) (6.0.2)
Requirement already satisfied: chardet<5.0,>=2.0 in d:\vkbot\discordbot-master\venv\lib\site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py==1.7.3->-r requirements.txt (line 6)) (4.0.0)
Requirement already satisfied: async-timeout<4.0,>=3.0 in d:\vkbot\discordbot-master\venv\lib\site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py==1.7.3->-r requirements.txt (line 6)) (3.0.1)
Requirement already satisfied: attrs>=17.3.0 in d:\vkbot\discordbot-master\venv\lib\site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py==1.7.3->-r requirements.txt (line 6)) (22.1.0)
Requirement already satisfied: typing-extensions>=3.6.5 in d:\vkbot\discordbot-master\venv\lib\site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py==1.7.3->-r requirements.txt (line 6)) (4.3.0)
Requirement already satisfied: yarl<2.0,>=1.0 in d:\vkbot\discordbot-master\venv\lib\site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py==1.7.3->-r requirements.txt (line 6)) (1.8.1)
Requirement already satisfied: pycparser in d:\vkbot\discordbot-master\venv\lib\site-packages (from cffi>=1.4.1->PyNaCl==1.5.0->-r requirements.txt (line 7)) (2.21)

**Comment by ILUXASAN** [comment]
(venv) D:\VKBOT\DiscordBot-master>pip list
Package            Version
------------------ -----------
aiohttp            3.7.4.post0
async-timeout      3.0.1
attrs              22.1.0
beautifulsoup4     4.11.1
certifi            2022.6.15
cffi               1.15.1
chardet            4.0.0
charset-normalizer 2.1.1
discord.py         1.7.3
idna               3.3
iso8601            1.0.2
m3u8               2.0.0
multidict          6.0.2
natsort            8.1.0
pip                22.2.2
pycparser          2.21
pycryptodome       3.15.0
PyNaCl             1.5.0
requests           2.28.1
setuptools         63.4.1
soupsieve          2.3.2.post1
typing_extensions  4.3.0
urllib3            1.26.11
vk-api             11.9.9
wheel              0.37.1
yarl               1.8.1

**Comment by tachycardiazxc** [comment]
попробуй это
pip install -U discord.py[voice]

**Comment by ILUXASAN** [comment]
Теперь вообще бот не запускается
(venv) D:\VKBOT\DiscordBot-master>python main.py
Media folder checked...
Starting and configuring the bot...
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    bot = commands.Bot(command_prefix=commands.when_mentioned_or(DiscordCfg.COMMAND_PREFIX))
TypeError: __init__() missing 1 required keyword-only argument: 'intents'

**Comment by tachycardiazxc** [comment]
да, там ломаются интенты, щас гляну

**Comment by tachycardiazxc** [comment]
пока откатись обратно
pip install -U -r requirements.txt

**Comment by tachycardiazxc** [comment]
спуль ветку еще раз, выкатил небольшой хотфикс, прописал в requirements файле discord[voice], в теории может помочь, попробуй
как спулишь ветку еще раз пропиши
pip install -U -r requirements.txt

**Comment by tachycardiazxc** [comment]
хотя можешь просто написать в консоли
pip install -u discord.py[voice]==1.7.3

**Comment by ILUXASAN** [comment]
Я написал pip install discord.py[voice]==1.7.3, почему то на -u ругался pip
(venv) D:\VKBOT\DiscordBot>python main.py
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from src.discord_bot.client import Music
  File "D:\VKBOT\DiscordBot\src\discord_bot\client.py", line 1, in <module>
    from src.music_downloader.downloader import Downloader
  File "D:\VKBOT\DiscordBot\src\music_downloader\downloader.py", line 4, in <module>
    import m3u8
ModuleNotFoundError: No module named 'm3u8'

**Comment by tachycardiazxc** [comment]
а теперь он не видит m3u8 да че за прикол-то
pip install m3u8==2.0.0

**Comment by tachycardiazxc** [comment]
там просто -U с большой буквы обязательно писать, опечатался чутка

**Comment by ILUXASAN** [comment]
Опять что-то сломалось
(venv) D:\VKBOT\DiscordBot>python main.py
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from src.discord_bot.client import Music
  File "D:\VKBOT\DiscordBot\src\discord_bot\client.py", line 1, in <module>
    from src.music_downloader.downloader import Downloader
  File "D:\VKBOT\DiscordBot\src\music_downloader\downloader.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by tachycardiazxc** [comment]
у тебя полностью requirements слетел

**Comment by tachycardiazxc** [comment]
пропиши pip install -U -r requirements.txt

**Comment by tachycardiazxc** [comment]
блин, на самом деле можем созвониться в дискорде и разом все до ума довести, я заодно пойму что фиксить нужно будет

**Comment by tachycardiazxc** [comment]
tachycardiazxc#5519
набирай если не против
